### PR TITLE
Blank host should support signed records

### PR DESCRIPTION
**Pull request by aarshkshah1992**
We already do this in the `Host` now. So, we should also do it here for tests.

### CODE REVIEW

**Comment by Stebalien** [comment]
Don't we need to emit events, update this record when the addresses change, etc?

**Comment by aarshkshah1992** [comment]
@Stebalien We emit addr changes events when we want to in the Identify tests for now. I'm okay with making that change here too.

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
This is strictly speaking _better_. My point was that, to be a completely correct host implementation, we'd need to emit all the right events. But I'm fine filing an issue and fixing it later.

**Comment by aarshkshah1992** [comment]
@Stebalien Issue: https://github.com/libp2p/go-libp2p-blankhost/issues/43

**Pull request merged**
